services:
  postgres:
    image: postgres:14.7
    container_name: quartz_postgres
    restart: always
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
      POSTGRES_DB: scheduler
    ports:
      - "5432:5432"
    volumes:
      - quartz_pgdata:/var/lib/postgresql/data

volumes:
  quartz_pgdata:
